# Generated by Django 6.0.2 on 2026-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('venue', models.CharField(max_length=255, verbose_name='Площадка')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='WebPages_ev_date_9fa910_idx'), models.Index(fields=['slug'], name='WebPages_ev_slug_7a628d_idx')],
            },
        ),
    ]
