# Generated by Django 6.0.2 on 2026-04-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0002_category_event_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='WebPages.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
