# Generated by Django 6.0.2 on 2026-04-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0003_alter_event_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='WebPages.category', verbose_name='Категория'),
        ),
    ]
