# Generated by Django 6.0.2 on 2026-05-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0005_tag_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d/', verbose_name='Изображение мероприятия'),
        ),
    ]
